version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-nginx-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    command: ash -c "npm install && npm start"

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-nginx-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-nginx-network

networks:
  node-nginx-network:
    driver: bridge
